baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "COLLECTIVE IMPROVEMENT ASSOCIATION"
theme = "mcp-theme"

[params]
  description = "Your central hub for Maricopa activism to save our democracy"
  darkBlue = "#4d5061ff"
  lightBlue = "#7a7e91ff"
  beige = "#f9f5e3"
